services:
  antifraud-app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: antifraud-streamlit

    ports:
      - "8501:8501"

    volumes:
      # SQLite БД и логирование
      - ./database:/app/database

      # Предобученные модели
      - ./models:/app/models

    working_dir: /app

    restart: unless-stopped