[theme]
primaryColor="#dc719c"
backgroundColor="#f1d8e3"
secondaryBackgroundColor="#dcacc1"
textColor="#262730"
font="monospace"

[server]
maxUploadSize = 400  # Максимальный размер загружаемого файла, МБ

[browser]
pageTitle = "Фрод-мониторинг: Выбор модели"